### ISSUE TITLE
Upstream Docker support

### ISSUE THREAD

**Issue by kuba** [JensErat/docker-lets-encrypt-preview#2]
As of https://github.com/letsencrypt/lets-encrypt-preview/pull/437 upstream project supports Docker in the `master` branch, images are automatically built at https://quay.io/repository/letsencrypt/lets-encrypt-preview. Please consider making an appropriate notice in your `README.md`. You are more than welcome to contribute!

**Comment by JensErat** [comment]
Upstream support for Docker is great news!

Is there anything stopping you from making it an automated build in the Docker registry, too? Reading the Dockerfile I don't see anything that should be stopping you.
